dist: xenial
addons:
  apt:
    packages:
    - g++
    - cmake
    - libboost-all-dev
    - libssl-dev

language: c++
compiler: g++

install:
  - cmake .
  - make
script:
  - ./kms-server & ./test_runner
