dist: xenial
addons:
  apt:
    packages:
    - g++
    - cmake
    - libboost-all-dev
    - libssl-dev

language: c++
compiler: g++

install:
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make
script:
  - ./kms_server && sleep 1 & ./test_runner
